FROM node:21

WORKDIR /usr/src/app

RUN rm -rf package.json node_modules package-lock.json
RUN npm install -g @nestjs/cli
COPY package*.json ./
RUN npm install
# prod
# RUN npm install

COPY . .

RUN npx prisma generate

# prod
# CMD ["npm", "run", "start:dev"]
CMD ["npm", "run", "start:dev"]