
FROM node:21

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

RUN apt-get update && apt-get install -y curl net-tools

COPY . .

RUN npx prisma generate

RUN npm run build

EXPOSE 3001

# CMD ["npm", "run", "start:dev"]
CMD ["node", "dist/main.js"]
